name: unpub_auth
description: An auth tool for unpub.
version: 0.1.1
homepage: https://github.com/bytedance/unpub

environment:
  sdk: ">=2.15.0 <3.0.0"

executables:
  unpub_auth:

dependencies:
  console: ^4.1.0
  dotenv: ^4.0.1
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  lints: ^1.0.0

assets:
  - .env
