name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  unpub:
    git:
      url: https://github.com/paddo/unpub.git
      path: unpub/
  minio: ^3.5.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  chunked_stream: ^1.4.1
  mockito: ^5.2.0
  build_runner: ^2.2.0
  path: ^1.8.2
  json_annotation: ^4.6.0
dependency_overrides:
  unpub:
    path: ../unpub
